### ISSUE TITLE
Missing FileEntry for /tmp/bayeux? 

### ISSUE THREAD

**Issue by HanFangXie** [SuperNEMO-DBD/SensitivityModule#21]
I am trying to run sensitivity module but got this error which I normally see before: 
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180921-39608-8yohue/Bayeux-3.3.0/bayeux.build/source/inc/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20180921-39608-8yohue/Bayeux-3.3.0/bayeux.build/source/inc/brio/detail/brio_record.h
   requested to autoload type brio_record
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: [void FLReconstruct::do_postprocess(FLReconstruct::FLReconstructParams &):430: Missing services configuration file!]

But it is so weird that I didn't get the processed sensitivity. root file. 

I am using macOS 10.13, falaise 3.3.0, bayeux 3.3.0, root 6.12.04.

**Comment by cherylepatrick** [comment]
Can you run other flreconstruct modules? This might not be a SensitivityModule bug.

**Comment by HanFangXie** [comment]
Yes. I agree. It was working before.  Also, I can't run other modules as well. I thought there might not be a SensitivityModule bug. I will keep testing and report it here if I fixed this problem.

**Comment by cherylepatrick** [comment]
Did you maybe upgrade anything? Falaise or Bayeux? You could try doing a brew update/upgrade and see if that helps.

**Comment by HanFangXie** [comment]
Sure. I will try brew update/upgrade. I think my reconstruct is not working properly.

**Comment by cherylepatrick** [comment]
You could try downgrading bayeux - I had problems with 3.3 and downgraded to 3.1.2 (brew switch, I think is the command)

**Comment by drbenmorgan** [comment]
The cling error can be safely ignored. I think you may be running into this error:

https://github.com/SuperNEMO-DBD/Falaise/issues/15

What file are you trying to read? Has it been generated recently, or is from a while ago?

**Comment by drbenmorgan** [comment]
> You could try downgrading bayeux - I had problems with 3.3 and downgraded to 3.1.2 (brew switch, I think is the command)

I'd be very careful about this - they *should* be compatible, but the latest Falaise release does need some functionality from Bayeux 3.3

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - noted. Will try and get it all in line again when Prague is over with. Anyway I am hijacking Fang's issue.

**Comment by drbenmorgan** [comment]
Closing this as out of date
