### ISSUE TITLE
for all 1engamma events, reco.angle_between_tracks value -9999

### ISSUE THREAD

**Issue by HanFangXie** [SuperNEMO-DBD/SensitivityModule#22]
Scanned 1E6 events but 0 event passed the cut "reco.topology_1engamma==1&&reco.angle_between_tracks!=-9999"

I can see the correct gamma and electron tracks using flvisualize. 
SO it does not seem to be problems with gamma tracking.

Sample: Tl208_source_pads_bulk_Mapped_rec_1E6.brio  and the corresponding sensitivity.root file

Sensitivity Module: AlphasFromFoil version and Lauren’sVersion

Reconstruction: Offcial_reconstruction.conf (gamma clusterizer problem fixed)

**Comment by cherylepatrick** [comment]
You're right - the documentation is wrong here. It calculates the angle for 1e1alpha and 2e topologies. But it's a good idea to add it for 1e-n gamma events. I would suggest using gamma tracking information to calculate it if and only if there is a gamma associated to the electron vertex, and to calculate the angle between those two tracks. It will only work if you have gamma tracking working. For now I will update the documentation to match what it does.

**Comment by cherylepatrick** [comment]
I've updated the readme to make it clearer how it currently works. If you want to have a  go at adding the 1e-n gamma angles, and testing that it works, that would be great.

**Comment by cherylepatrick** [comment]
Should be fixed by #24

**Comment by cherylepatrick** [comment]
@HanFangXie @wausain - please can you test PR #24 and let me know if this works as expected?

**Comment by cherylepatrick** [comment]
Closing after testing by @HanFangXie
