### ISSUE TITLE
Failing loading the module with flreconstruct

### ISSUE THREAD

**Issue by pfranchini** [SuperNEMO-DBD/SensitivityModule#25]
Hi,

I have successfully built the module but once I run any sort of test using it I get 
```
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'SensitivityModule'...
[error:int datatools::library_loader::load(const string&, const string&, const string&, const string&, const string&):296] datatools::library_loader::load: The 'SensitivityModule' library was not loaded ! DATATOOLS_SYS_NAMESPACE says: '/home/hep/pfranchi/SuperNEMO/SensitivityModule/build/libSensitivityModule.so: undefined symbol: _ZNK9datatools15i_tree_dumpable10print_treeERSoRKN5boost13property_tree11basic_ptreeISsSsSt4lessISsEEE' !
flreconstruct : Setup/run of simulation threw exception
[void datatools::library_loader::_init():471: Automatic loading of library='SensitivityModule' failed !]
```
Thanks!

**Comment by drbenmorgan** [comment]
Hi @pfranchini, I'll see if I can reproduce this as the error message would imply either SensitivityModule needs linking to the Bayeux library, or that flreconstruct isn't supplying that symbol somehow. May take me until tomorrow to get to this though.

**Comment by pfranchini** [comment]
Thanks for that as usual, no rush, I will have a go myself.

**Comment by drbenmorgan** [comment]
Hi @pfranchini, I've tried this locally on CentOS7 and it seem to work for me with the following steps:

```console
$ ls
SensitivityModule.git
$ mkdir build
$ cd build
$ brew snemo-shell
snemo-shell> cmake ../SensitivityModule.git && make
snemo-shell> flsimulate -o test.brio
snemo-shell> flreconstruct -i test.brio -p "@falaise:config/snemo/demonstrator/reconstruction/official-2.0.0.conf" -o test-reco.brio
snemo-shell> flreconstruct -i test-reco.brio -p SensitivityModuleExample.conf
[notice:void datatools::library_loader::_init():467] Automatic loading of library 'SensitivityModule'...
In reset: finished conversion, file closed 
```

Could you check which versions of Falaise/Bayeux/Boost you have installed, and also if you have any env vars like `LD_LIBRARY_PATH` set? The missing symbol error would suggest a possible Bayeux version mismatch between your build and run of SensitivityModule.

**Comment by pfranchini** [comment]
Hi, coming back to this because I kind like running this better than the docker...
```
* Falaise : 3.3.0
* Bayeux  : 3.3.0
* Boost   : 106300
* Geant4  : 9.6.4
```
no `LD_LIBRARY_PATH` set, while

`PATH=/vols/build/snemo/brew/sbin:/vols/build/snemo/brew/bin:/vols/build/snemo/snemo-sdk/bin:/vols/build/snemo/snemo-sdk/sbin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/hep/pfranchi/.local/bin:/home/hep/pfranchi/bin`

Thanks!

**Comment by pfranchini** [comment]
I have been using it since many months so should close this.

The reason was that I was not building within the docker shell and using it with docker's `flreconstruct`.
