### ISSUE TITLE
Implement a variable with a counter for all the vertices on the foil

### ISSUE THREAD

**Issue by pfranchini** [SuperNEMO-DBD/SensitivityModule#26]
The current variable `reco.vertices_on_foil` counts either vertices on foil or on wire, so the name is a bit misleading (or at least was for me).

The idea is
- renaming this one (so people using this variable for the wrong purpose will spot it out updating the code)
- creating a new one like `reco.foil_vertex_count` (similar of `reco.calorimeter_hit_count`) counting the vertices on the foil for each event
- update the README.md

This has been discussed in https://github.com/SuperNEMO-DBD/Falaise/issues/142.

**Comment by cherylepatrick** [comment]
Fixed by #27
