### ISSUE TITLE
Divid by 0 fatal error

### ISSUE THREAD

**Issue by willquinn** [SuperNEMO-DBD/SensitivityModule#36]
Using the latest Falaise develop branch build, running `$ flreconstruct -i input_reco.brio -p SensitivityModuleExample.conf` on a 50000 event reconstructed .brio file, the output error is:
[error.txt](https://github.com/SuperNEMO-DBD/SensitivityModule/files/5932042/error.txt)

The brio file can be found at /sps/nemo/scratch/simu/wquinn/damned_sn_reco_210204001/output_files.d/file_0.brio which I have made readable. The problem event is event 28520 - see a picture here:
<img width="1090" alt="Screenshot 2021-02-05 at 11 20 14" src="https://user-images.githubusercontent.com/44215491/107027530-2c45c700-67a4-11eb-9007-3ad5efa6386c.png">

* Falaise : 4.0.3
* Bayeux  : 3.4.2
* Boost   : 106900

**Comment by cherylepatrick** [comment]
If you look at that last particle, it has a zero-length track - both vertices are in the same place. That particle's a bug in the reconstruction, but we ought to handle it gracefully in SM. I am moderately sure we fixed this once already, as we used track lengths for the internal/external prob calculations, so my guess is that something else is looking at track lengths. And as this is an undefined charged particle it could be the alpha length finder. Can you check the code and look for something that is trying to divide by a track length? Then you need to add a check that the length of the track is not zero, and if it is, abort the mission.

**Comment by cherylepatrick** [comment]
I dunno what it thinks it has fitted but those fits are beyond garbage, look at the chi squares... how did the clustering go?

**Comment by drbenmorgan** [comment]
Fixed by #37
